# Generated by Django 4.2.5 on 2023-09-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_alter_menuitem_id_menuitemdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuItemDetail',
        ),
    ]
